### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by seitzbg** [dun/conman#25]
Any chance of adding Debian packaging support as well?

TIA,

**Comment by dun** [comment]
0.2.7 is in jessie-backports, stretch, and sid:

https://packages.debian.org/search?keywords=conman&searchon=names&exact=1&suite=all&section=all

Looks like 0.2.8 hasn't been picked up yet.

**Comment by seitzbg** [comment]
Yeah would just be easier if it was in the git repo here too :)
