### ISSUE TITLE
RFE: support a port argument for ipmi devices

### ISSUE THREAD

**Issue by larsks** [dun/conman#31]
I wanted to use conman for ipmi serial-over-lan access in a test environment where we're running a simulated bmc on nonstandard ports.  I was hoping I could simply use something like this:

    dev=ipmi:somehost:6230

It doesn't look like the code current knows how to parse out the port information.

**Comment by larsks** [comment]
Hmm, it looks as if this may actually be supported directly by `freeipmi`, although my attempts to get it working so far have failed.  Closing for now while I investigate.

**Comment by dun** [comment]
@larsks: I don't see a means of specifying an alternate port in `<ipmiconsole.h>`. Hmm...

@chu11: Hey Al, does the API support contacting the bmc on nonstandard ports?

**Comment by larsks** [comment]
@dun e.g., [here](http://git.savannah.gnu.org/cgit/freeipmi.git/tree/libfreeipmi/api/ipmi-api.c#n345) and elsewhere in the code that calls `host_is_host_with_port()`, which looks for a `:` in the hostname.

**Comment by chu11** [comment]
Yes, the hostname can be specified with `hostname:port` format.  I see I didn't document that in the ipmiconsole header.  I'll adjust the comment to indicate that.

**Comment by dun** [comment]
OK, when parsing a `dev=` keyword from a console directive, `conmand` takes everything after `ipmi:` as the hostname and passes that string on to `ipmiconsole_ctx_create()` [server-ipmi.c:create_ipmi_ctx()].

Config file "myconf":
```
console name="foo" dev="ipmi:127.0.0.1:1234"
```

Listening for UDP connections on port 1234:
```
$ nc -l -u 1234
```

Starting conmand:
```
$ DEBUG=10 ./conmand -c myconf -F
Opened config "myconf": fd=5.
Created object [foo].
 IPMI [foo] H:127.0.0.1:1234 U: P: K: L:-1 C:-1 W:0xFFFFFFFF
...
Connecting to <127.0.0.1:1234> via IPMI for [foo].
Opened [foo] via IPMI: fd=-1 host=127.0.0.1:1234 state=1.
```

I see output from `nc` when `conmand` connects. Looks like it's connecting to the specified port.

**Comment by larsks** [comment]
Yeah, it all looks as if it should work.  I need to take a closer look at what's failing in my environment.
